name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    strategy:
      matrix: # This iterates through all the below folders
        folder:
          - ConsoleSearch
          - LoadBalancerAPI
          - Renamer
          - SearchAPI
          - WebSearch
          - indexer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # I stole this from https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Downcase folder name
        run: |
          echo "FOLDER=$(echo ${{ matrix.folder }} | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}
        
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.folder }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.FOLDER }}:latest
